# Generated by Django 5.2 on 2025-05-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutrequest',
            name='days_per_week_preference',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='workoutrequest',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='workoutrequest',
            name='specific_focus_areas',
            field=models.TextField(blank=True),
        ),
    ]
