# Generated by Django 5.2 on 2025-05-10 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('currency', models.CharField(default='IRT', max_length=3)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('max_requests', models.PositiveIntegerField(default=10, help_text='Max AI generation requests for this tier during its duration')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending_payment', 'Pending Payment'), ('canceled', 'Canceled')], default='expired', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('latest_payment_transaction_id', models.CharField(blank=True, help_text="Gateway's transaction ID for the latest payment", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plantier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_transaction_id', models.CharField(help_text='Transaction ID from payment gateway (e.g., Zarinpal Authority)', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('verified', 'Verified & Processed')], default='pending', max_length=20)),
                ('payment_gateway', models.CharField(default='zarinpal', max_length=50)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('verification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('gateway_response_on_request', models.JSONField(blank=True, help_text='Full response from gateway on payment request', null=True)),
                ('gateway_response_on_verify', models.JSONField(blank=True, help_text='Full response from gateway on payment verification', null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('plan_tier_purchased', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plantier')),
                ('user_subscription_updated', models.ForeignKey(blank=True, help_text='The subscription record this payment updated/created', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.usersubscription')),
            ],
        ),
    ]
